language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update
  - composer require silverstripe/recipe-cms ^1

script:
  - php vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
  - cd ~/build/$TRAVIS_REPO_SLUG
  - bash <(curl -s https://codecov.io/bash)
